### ISSUE TITLE
Проверить ДЗ по веб серверу

### ISSUE THREAD

**Issue by HelgaJava** [HelgaJava/git-homework9WebServer#1]
Дублирую сюда вопросы из телеграмм:
2. Сервер отдает файлы, но при этом все равно выходит список исключений:
java.net.SocketException: Connection reset by peer: socket write error
  at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
  at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
  at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
  at java.base/java.io.InputStream.transferTo(InputStream.java:705)
  at java.base/java.nio.file.Files.copy(Files.java:3119)
  at ru.itpark.StaticWebServer.main(StaticWebServer.java:40)
Строка 40 - это: Files.copy(requestPath, out);
3. Если вводишь после запуска сервера разные файлы, то все равно отрабатывает NullPointerException. Т.е. запускаю сервер, ввожу путь с названием первого файла, все ОК, далее ввожу путь с названием 2-го файл и тут NullPointerException
+еще 1 вопрос: в коде есть комментированные строки, этот кусок кода не отрабатывает, хотела получить информацию хотя бы о количестве файлов в каталоге. Что я не так делаю?

**Comment by coursar** [comment]
1. Связано это с тем, что браузер, если имеет встроенный проигрыватель, после первого запроса и получения размера файла закрывает соединение и делает второй запрос типа range (https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) - можно, конечно, это отследить, но мы для простоты не разбирали
2. Не удалось воспроизвести
3. Вы не можете одновременно отдавать и файл и строки - браузер вас не поймёт - вам нужен отдельный урл, типа "/statistics", на который вы будете писать в ответ статистику

**Comment by HelgaJava** [comment]
По п.1 и 3 так и оставлять?

**Comment by coursar** [comment]
Можно, конечно, докрутить )) но для этого придётся ещё много чего дополнительно изучать. По п.3 нужно было создать `if` на `GET /statistics` и там выдавать статистику.
